application: wc-app
version: 0
runtime: python27
api_version: 1
threadsafe: true

# Handlers tell App Engine how to route requests to your application.
handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html

- url: /robots.txt
  static_files: dist/robots.txt
  upload: dist/robots.txt

- url: /bower_components
  static_dir: dist/bower_components

- url: /images
  static_dir: dist/images

- url: /scripts
  static_dir: dist/scripts

- url: /styles
  static_dir: dist/styles

- url: /views
  static_dir: dist/views

- url: /404.html
  static_files: dist/404.html
  static_dir: dist/404.html

- url: /robots.txt
  static_files: dist/robots.txt
  upload: dist/robots.txt

- url: /favicon.ico
  static_files: dist/favicon.ico
  upload: dist/favicon.ico



- url: /api.*
  script: main.app


# Third party libraries that are included in the App Engine SDK must be listed
# here if you want to use them. See
# https://developers.google.com/appengine/docs/python/tools/libraries27 for
# a list of libraries included in the SDK. Third party libs that are *not* part
# of the App Engine SDK don't need to be listed here, instead add them to your
# project directory, either as a git submodule or as a plain subdirectory.
# Note that dependencies must be located in your project directory - packages
# installed in the Python environment are not loaded by the App Engine
# development server or deployment tools.
#libraries:

# The pycrypto library is used for OAuth 2, and is also a requirement for
# APIs that wish to authenticate users.
#- name: pycrypto
#  version: latest

pagespeed:
  enabled_rewriters:
  - RemoveComments
  - ElideAttributes
  - ImageAddDimensions

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?.*\.coffee$
  - ^(.*/)?.*\.gzip$
  - ^(.*/)?.*\.lock$
  - ^(.*/)?.*\.map$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.mdown$
  - ^(.*/)?.*\.php$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*\.scss$
  - ^(.*/)?.*~$
  - ^(.*/)?\..*$
  - ^(.*/)?Gemfile$
  - ^(.*/)?Rakefile$
  - ^.*CHANGES.*$
  - ^.*LICENCE.*$
  - ^.*LICENSE.*$
  - node_modules
  - spec
  - test
  - app
  - app_
  - bower_components
  - ^env/src
  - ^env/man
  - ^.*[\(\)].*$