application: wc-app
version: 0
runtime: python27
api_version: 1
threadsafe: true

# Handlers tell App Engine how to route requests to your application.
handlers:
- url: /robots.txt
  static_files: dist/robots.txt
  upload: dist/robots.txt

- url: /favicon.ico
  static_files: dist/favicon.ico
  upload: dist/favicon.ico

- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application

- url: /media/admin
  static_dir: gaenv/django/contrib/admin/media
  expiration: '0'

- url: /static/admin
  static_dir: gaenv/django/contrib/admin/static/admin
  expiration: '0'

- url: /static/rest_framework
  static_dir: gaenv/rest_framework/static/rest_framework
  expiration: '0'

- url: /.*
  script: djangoappengine.main.application

# # This handler routes requests to your APIs to your Endpoints code.
# # See https://developers.google.com/appengine/docs/python/endpoints/
# - url: /_ah/spi/.*
#   script: wc_api.APPLICATION

env_variables:
  DJANGO_SETTINGS_MODULE: 'project.settings'


# Third party libraries that are included in the App Engine SDK must be listed
# here if you want to use them. See
# https://developers.google.com/appengine/docs/python/tools/libraries27 for
# a list of libraries included in the SDK. Third party libs that are *not* part
# of the App Engine SDK don't need to be listed here, instead add them to your
# project directory, either as a git submodule or as a plain subdirectory.
# Note that dependencies must be located in your project directory - packages
# installed in the Python environment are not loaded by the App Engine
# development server or deployment tools.
# TODO: List any other App Engine SDK libs you may need here.
# libraries:

# # You must include the Endpoints library if you wish to serve an API.
# - name: endpoints
#   version: 1.0

libraries:
- name: pycrypto
  version: latest

pagespeed:
  enabled_rewriters:
  - RemoveComments
  - ElideAttributes
  - ImageAddDimensions

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?.*\.coffee$
  - ^(.*/)?.*\.gzip$
  - ^(.*/)?.*\.lock$
  - ^(.*/)?.*\.map$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.mdown$
  - ^(.*/)?.*\.php$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*\.scss$
  - ^(.*/)?.*~$
  - ^(.*/)?\..*$
  - ^(.*/)?Gemfile$
  - ^(.*/)?Rakefile$
  - ^.*CHANGES.*$
  - ^.*LICENCE.*$
  - ^.*LICENSE.*$
  - node_modules
  - spec
  - .gaedata
  - ^env/.*
  - src
  - build
  - ^(.*/)?.*/tests/.*$